#!/usr/bin/env bash
# Develop this checkout.
#
#   etc/dev.sh build          compile the app (slow the first time; do this once)
#   etc/dev.sh run            start it — prints MH_READY when the port is live
#   etc/dev.sh reset          wipe the database back to fresh seed data
#
#   etc/dev.sh -- <cmd...>    run one command with this instance's env, in its
#                             own build dir (e.g. -- cargo check ...)
#   etc/dev.sh clean          remove all dev instances, volumes, generated envs
#
# `build` and `run` start the containers themselves; there is nothing to do
# first. Everything below the dispatch is plumbing you should not need to read.
set -euo pipefail

# ══ commands ════════════════════════════════════════════════════════════════
# The whole user-facing surface. Everything they call lives further down.

main() {
  case "${1:-}" in
    build)       shift; cmd_build "$@" ;;
    run)         shift; cmd_run "$@" ;;
    reset)       shift; cmd_reset "$@" ;;
    clean)       shift; cmd_clean "$@" ;;
    --)          shift; cmd_oneshot "$@" ;;
    -h|--help|"") usage ;;
    *)           usage >&2; exit 1 ;;
  esac
}

# Prints the header block above, so the usage text exists in exactly one place.
usage() {
  awk '/^# `build`/{exit} NR>1 && /^#/{sub(/^# ?/, ""); print}' "$0"
}

# All the cold-build cost lives here, so `run` starts quickly and a caller's
# readiness timeout never has to cover a compile.
cmd_build() {
  instance_up
  ( set -a; . "$ENV_LOCAL"; set +a; cd "$REPO_ROOT"; cargo leptos build )
  echo "Build complete for '$SLUG'. Start it with: etc/dev.sh run"
}

# Run the previously built app in the foreground. This never watches or compiles.
cmd_run() {
  trap instance_stop EXIT
  instance_up
  set -a; . "$ENV_LOCAL"; set +a
  cd "$REPO_ROOT"

  # Refuse to run unbuilt. A cold `cargo leptos` build takes many minutes and
  # would be invisible to a caller waiting on readiness.
  if [ ! -x "$DEV_BINARY" ] \
      || ! compgen -G "$REPO_ROOT/target/site/pkg/*" >/dev/null 2>&1; then
    echo "dev: not built yet — run 'etc/dev.sh build' first" >&2
    exit 1
  fi

  echo "Starting '$MH_INSTANCE' on http://$LEPTOS_SITE_ADDR"
  run_and_await_readiness "$DEV_BINARY" "$@"
}

cmd_reset() {
  if [ "${1:-}" = --rebuild-seed ]; then build_seed_image force; fi
  build_seed_image
  remove_container "$DB_CONTAINER"
  "$DOCKER" volume rm "$DB_VOLUME" >/dev/null 2>&1 || true
  instance_up
  echo "Database reset to fresh seed data."
}

# Remove every dev instance. Shared seed images and dumps remain cached.
cmd_clean() {
  local name file root env_file

  while read -r name; do
    [ -n "$name" ] && remove_container "$name"
  done < <(docker_names --all | grep -E '^mh-(db|storage|seedbuild)-' || true)

  while read -r name; do
    [ -n "$name" ] && "$DOCKER" volume rm "$name" >/dev/null 2>&1 || true
  done < <(docker_volumes | grep -E '^mh-(pgdata|blobdata|dbdata)-' || true)

  mkdir -p "$PORT_DIR"
  exec {port_lock_fd}>"$PORT_LOCK"
  flock "$port_lock_fd"
  for file in "$PORT_DIR"/*; do
    [ -f "$file" ] || continue
    [ "$file" = "$PORT_LOCK" ] && continue
    IFS=$'\t' read -r _ root <"$file" || true
    env_file="${root:-}/.env.local"
    if [ -f "$env_file" ] \
        && grep -qE '^# GENERATED by etc/(dev\.sh|dev-db\.sh)' "$env_file"; then
      rm -f "$env_file"
    fi
    rm -f "$file"
  done
  echo "Removed all Mommy's Heart dev instances, volumes, generated envs, and ports."
}

# One-off commands get their own build directory. Sharing `target/` with
# cargo-leptos makes the different SSR-only and SSR+hydrate feature sets
# invalidate each other's fingerprints and slows subsequent builds.
cmd_oneshot() {
  instance_up
  set -a; . "$ENV_LOCAL"; set +a
  cd "$REPO_ROOT"
  export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$REPO_ROOT/target/oneshot}"
  exec "$@"
}

# ══ plumbing ════════════════════════════════════════════════════════════════
# Every checkout gets its OWN containers, so any number of agents can work at
# the same time without coordinating (via Docker):
#   * mh-db-<instance>       — PostgreSQL, comes up already seeded
#   * mh-storage-<instance>  — Azurite, the Azure Storage emulator for evidence
#
# Names and ports derive from an *instance slug* (the checkout's directory name
# plus a path hash by default), written to a git-ignored .env.local the app and
# this script both read.
#
# Fast seeding: running the Rust seeder is slow (it compiles the SSR binary and
# argon2-hashes every demo password). So we do it once, dump the result, and
# bake the dump into a database *image* tagged with a fingerprint of the
# migrations + seed sources. A container from that image is seeded in ~3s.
# Editing a migration or the fixtures changes the fingerprint, so a new image is
# built while other agents keep using theirs. Images are immutable and the
# runtime refuses to delete one in use, so this needs no bookkeeping from us.

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEV_BINARY="$REPO_ROOT/target/debug/mommys-heart-app"
DOCKER="${DOCKER:-docker}"
ENV_LOCAL="$REPO_ROOT/.env.local"
CACHE_DIR="${MH_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/mommys-heart-devdb}"
PORT_DIR="$CACHE_DIR/ports"

POSTGRES_USER="${POSTGRES_USER:-mommysheart}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-localdev}"
POSTGRES_DB="${POSTGRES_DB:-mommysheart}"
DB_BASE_IMAGE="${MH_DB_IMAGE:-postgres:16}"
STORAGE_IMAGE="${MH_STORAGE_IMAGE:-mcr.microsoft.com/azure-storage/azurite}"

# ── instance identity ───────────────────────────────────────────────────────
# The readable prefix identifies the checkout; the hash prevents equal,
# sanitized or truncated directory names in different paths from colliding.
# MH_INSTANCE participates in both so it can select another instance in one
# checkout without losing worktree isolation.
INSTANCE_NAME="${MH_INSTANCE:-$(basename "$REPO_ROOT")}"
INSTANCE_HASH="$(printf '%s\0%s' "$REPO_ROOT" "${MH_INSTANCE:-}" | sha256sum | cut -c1-8)"
SLUG_PREFIX="$(printf '%s' "$INSTANCE_NAME" \
  | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-' \
  | sed -e 's/-\+/-/g' -e 's/^-//' -e 's/-$//')"
SLUG_PREFIX="${SLUG_PREFIX:0:31}"; [ -n "$SLUG_PREFIX" ] || SLUG_PREFIX="default"
SLUG="$SLUG_PREFIX-$INSTANCE_HASH"

DB_CONTAINER="mh-db-$SLUG"
STORAGE_CONTAINER="mh-storage-$SLUG"
DB_VOLUME="mh-pgdata-$SLUG"
STORAGE_VOLUME="mh-blobdata-$SLUG"

# ── ports ───────────────────────────────────────────────────────────────────
# One contiguous block of four: web, live-reload, postgres, blob. Assignments
# are persisted in the shared cache so stopped containers retain their ports.
# Allocation is locked so simultaneous worktree starts cannot claim one block.
port_free() {
  ! ss -ltn "sport = :$1" 2>/dev/null | grep -q LISTEN
}

pinned_env() {
  [ -f "$ENV_LOCAL" ] || return 1
  local v; v="$(grep -m1 "^$1=" "$ENV_LOCAL" 2>/dev/null)" || return 1
  v="${v#*=}"; v="${v%\"}"; printf '%s' "${v#\"}"
}

owns_env_local() { [ "$(pinned_env MH_INSTANCE 2>/dev/null || true)" = "$SLUG" ]; }

PORT_FILE="$PORT_DIR/$INSTANCE_HASH"
PORT_LOCK="$PORT_DIR/.lock"

reservation_base() {
  [ -f "$1" ] || return 1
  local base _root
  IFS=$'\t' read -r base _root <"$1" || return 1
  [[ "$base" =~ ^[0-9]+$ ]] || return 1
  printf '%s' "$base"
}

block_reserved_by_other() {
  local candidate="$1" file reserved
  for file in "$PORT_DIR"/*; do
    [ -f "$file" ] || continue
    [ "$file" = "$PORT_FILE" ] && continue
    reserved="$(reservation_base "$file" 2>/dev/null || true)"
    [ "$reserved" = "$candidate" ] && return 0
  done
  return 1
}

find_free_port() {
  local p
  for ((p = 3900; p < 4000; p++)); do port_free "$p" && { printf '%s' "$p"; return 0; }; done
  echo "dev: no free port in 3900-3999" >&2; return 1
}

find_base_port() {
  local start i j base ok
  start=$(( 16#$(printf '%s' "$SLUG" | sha256sum | cut -c1-8) % 200 ))
  for ((i = 0; i < 200; i++)); do
    base=$(( 3100 + (((start + i) % 200) * 4) ))
    block_reserved_by_other "$base" && continue
    ok=1
    for ((j = 0; j < 4; j++)); do port_free $((base + j)) || { ok=0; break; }; done
    [ "$ok" = 1 ] && { printf '%s' "$base"; return 0; }
  done
  echo "dev: no free block of 4 ports in 3100-3899" >&2; return 1
}

allocate_base_port() {
  mkdir -p "$PORT_DIR"
  local base pinned file reserved_root
  exec {port_lock_fd}>"$PORT_LOCK"
  flock "$port_lock_fd"

  # Removed worktrees cannot release their reservation. Reclaim
  # those entries while preserving stopped instances whose checkout still exists.
  for file in "$PORT_DIR"/*; do
    [ -f "$file" ] || continue
    IFS=$'\t' read -r base reserved_root <"$file" || true
    [ -n "${reserved_root:-}" ] && [ ! -d "$reserved_root" ] && rm -f "$file"
  done

  base="$(reservation_base "$PORT_FILE" 2>/dev/null || true)"
  if [ -z "$base" ] && owns_env_local; then
    pinned="$(pinned_env LEPTOS_SITE_ADDR 2>/dev/null || true)"
    pinned="${pinned##*:}"
    if [[ "$pinned" =~ ^[0-9]+$ ]] && ! block_reserved_by_other "$pinned"; then
      base="$pinned"
    fi
  fi
  if [ -z "$base" ] && [ -n "${MH_BASE_PORT:-}" ]; then
    [[ "$MH_BASE_PORT" =~ ^[0-9]+$ ]] || { echo "dev: MH_BASE_PORT must be numeric" >&2; return 1; }
    ! block_reserved_by_other "$MH_BASE_PORT" || { echo "dev: port block $MH_BASE_PORT is reserved" >&2; return 1; }
    for ((p = MH_BASE_PORT; p < MH_BASE_PORT + 4; p++)); do
      port_free "$p" || { echo "dev: port $p is already in use" >&2; return 1; }
    done
    base="$MH_BASE_PORT"
  fi
  [ -n "$base" ] || base="$(find_base_port)"
  printf '%s\t%s\n' "$base" "$REPO_ROOT" >"$PORT_FILE.tmp.$$"
  mv "$PORT_FILE.tmp.$$" "$PORT_FILE"
  printf '%s' "$base"
}

BASE_PORT="$(allocate_base_port)"
SITE_PORT=$BASE_PORT
RELOAD_PORT=$((BASE_PORT + 1))
DB_PORT=$((BASE_PORT + 2))
BLOB_PORT=$((BASE_PORT + 3))

DATABASE_URL_VALUE="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:$DB_PORT/$POSTGRES_DB"
# Azurite's public, well-known development credentials (not a secret).
STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:$BLOB_PORT/devstoreaccount1;"

# ── seed image ──────────────────────────────────────────────────────────────
FINGERPRINT="$(cat "$REPO_ROOT"/migrations/*.sql "$REPO_ROOT/src/mockdata.rs" \
  "$REPO_ROOT/src/server/db/seed.rs" 2>/dev/null | sha256sum | cut -c1-12)"
SEED_IMAGE="mommys-heart-devdb:$FINGERPRINT"
CACHE_FILE="$CACHE_DIR/seed-$FINGERPRINT.sql"

# List exact container names for reliable matching.
docker_names() {
  if [ -n "${1:-}" ]; then
    "$DOCKER" ps "$1" --format '{{.Names}}' 2>/dev/null
  else
    "$DOCKER" ps --format '{{.Names}}' 2>/dev/null
  fi
}

container_running() { docker_names | grep -qx "$1"; }
container_exists() { docker_names --all | grep -qx "$1"; }

remove_container() {
  container_exists "$1" || return 0
  "$DOCKER" stop "$1" >/dev/null 2>&1 || true
  "$DOCKER" rm "$1" >/dev/null 2>&1 || true
}

docker_volumes() {
  "$DOCKER" volume list --format '{{.Name}}' 2>/dev/null
}

# A run owns its current containers only; stopping preserves their volumes/data.
instance_stop() {
  "$DOCKER" stop "$DB_CONTAINER" >/dev/null 2>&1 || true
  "$DOCKER" stop "$STORAGE_CONTAINER" >/dev/null 2>&1 || true
}

# Seed once into a scratch container and cache the dump. The cache is keyed by
# fingerprint and shared by every checkout, so this normally runs once per
# machine per schema change. Concurrent builders are harmless: they do the same
# work and the final `mv` is atomic.
build_seed_dump() {
  [ -s "$CACHE_FILE" ] && { touch "$CACHE_FILE"; return; }
  mkdir -p "$CACHE_DIR"

  local scratch="mh-seedbuild-$FINGERPRINT" seed_port
  # Its own free port: the instance's DB_PORT may still be held by a running
  # container (during `reset`), and another agent may be seeding concurrently.
  seed_port="$(find_free_port)"
  echo "Seeding once to build '$SEED_IMAGE' (first time for these migrations/fixtures)."
  echo "This runs the Rust seeder; the result is cached and reused by every instance."

  remove_container "$scratch"
  "$DOCKER" run -d --name "$scratch" -e "POSTGRES_USER=$POSTGRES_USER" \
    -e "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" -e "POSTGRES_DB=$POSTGRES_DB" \
    -p "$seed_port:5432" "$DB_BASE_IMAGE" >/dev/null

  local tries=60
  until "$DOCKER" exec "$scratch" pg_isready -U "$POSTGRES_USER" -q >/dev/null 2>&1; do
    ((tries-- > 0)) || { remove_container "$scratch"; echo "dev: scratch container never became ready" >&2; return 1; }
    sleep 1
  done

  ( cd "$REPO_ROOT" && DATABASE_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:$seed_port/$POSTGRES_DB" \
      CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$REPO_ROOT/target/oneshot}" \
      RUST_LOG="${MH_SEED_LOG:-info}" cargo run --quiet --no-default-features --features ssr -- seed \
  ) || { remove_container "$scratch"; return 1; }

  "$DOCKER" exec "$scratch" pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
    --no-owner --no-privileges >"$CACHE_FILE.tmp"
  mv "$CACHE_FILE.tmp" "$CACHE_FILE"
  remove_container "$scratch"
  # Dumps are ~60KB; keep anything used in the last 30 days.
  find "$CACHE_DIR" -maxdepth 1 -name 'seed-*.sql' -mtime +30 -delete 2>/dev/null || true
}

# Bake the dump into an image. Postgres replays docker-entrypoint-initdb.d the
# first time a container initializes its data directory, which is what makes a
# fresh container come up already seeded.
build_seed_image_unlocked() {
  if [ "${1:-}" = force ]; then
    rm -f "$CACHE_FILE"; "$DOCKER" rmi -f "$SEED_IMAGE" >/dev/null 2>&1 || true
  elif "$DOCKER" images --format '{{.Repository}}:{{.Tag}}' 2>/dev/null | grep -qx "$SEED_IMAGE"; then
    return
  fi

  build_seed_dump
  local ctx; ctx="$(mktemp -d)"
  cp "$CACHE_FILE" "$ctx/seed.sql"
  printf 'FROM %s\nENV POSTGRES_USER=%s\nENV POSTGRES_PASSWORD=%s\nENV POSTGRES_DB=%s\nCOPY seed.sql /docker-entrypoint-initdb.d/10-seed.sql\n' \
    "$DB_BASE_IMAGE" "$POSTGRES_USER" "$POSTGRES_PASSWORD" "$POSTGRES_DB" >"$ctx/Dockerfile"
  echo "Baking seed image '$SEED_IMAGE'."
  "$DOCKER" build -t "$SEED_IMAGE" "$ctx" >/dev/null
  rm -rf "$ctx"
}

build_seed_image() {
  mkdir -p "$CACHE_DIR"
  local seed_lock="$CACHE_DIR/seed-$FINGERPRINT.lock" status
  exec {seed_lock_fd}>"$seed_lock"
  flock "$seed_lock_fd"
  if build_seed_image_unlocked "${1:-}"; then status=0; else status=$?; fi
  flock -u "$seed_lock_fd"
  exec {seed_lock_fd}>&-
  return "$status"
}

# ── containers ──────────────────────────────────────────────────────────────

# Wait until the database is not merely up but seeded: a fresh container replays
# the baked dump before opening for business.
wait_for_db() {
  # Probe over TCP, not the unix socket: while the seed image's init scripts run,
  # postgres listens on the socket only. A socket probe would report ready during
  # that bootstrap phase, just before the server restarts.
  # Redirect stdin: `docker exec -i` inherits the caller's stdin, and under a tty
  # (an IDE/tmux pane) psql waits for input forever instead of exiting.
  local tries=90
  until "$DOCKER" exec -i "$DB_CONTAINER" psql -h 127.0.0.1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
      -tAc "SELECT 1 FROM users LIMIT 1" </dev/null 2>/dev/null | grep -q 1; do
    ((tries-- > 0)) || { echo "dev: timed out waiting for '$DB_CONTAINER' (see: $DOCKER logs $DB_CONTAINER)" >&2; return 1; }
    sleep 1
  done
}

db_up() {
  build_seed_image
  if container_running "$DB_CONTAINER"; then :
  elif container_exists "$DB_CONTAINER"; then "$DOCKER" start "$DB_CONTAINER" >/dev/null
  else
    echo "Creating '$DB_CONTAINER' from '$SEED_IMAGE' (already seeded)."
    "$DOCKER" run -d --name "$DB_CONTAINER" -p "$DB_PORT:5432" \
      -v "$DB_VOLUME:/var/lib/postgresql/data" "$SEED_IMAGE" >/dev/null
  fi
  wait_for_db
}

storage_up() {
  container_running "$STORAGE_CONTAINER" && return 0
  if container_exists "$STORAGE_CONTAINER"; then
    "$DOCKER" start "$STORAGE_CONTAINER" >/dev/null
  else
    echo "Creating '$STORAGE_CONTAINER' ($STORAGE_IMAGE)."
    # --skipApiVersionCheck lets the newer Azure SDK's x-ms-version header work
    # against the emulator without pinning it to an exact Azurite release.
    "$DOCKER" run -d --name "$STORAGE_CONTAINER" -p "$BLOB_PORT:10000" \
      -v "$STORAGE_VOLUME:/data" "$STORAGE_IMAGE" \
      azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck >/dev/null
  fi
}

write_env_local() {
  # Values are quoted so the file works both for dotenvy (the app) and `source`
  # (etc/dev.sh) — the storage connection string contains ';'.
  cat >"$ENV_LOCAL" <<EOF
# GENERATED by etc/dev.sh — do not edit, do not commit.
# Per-instance overrides for '$SLUG'; take precedence over .env, but not over
# variables already exported in your shell. Regenerated by each dev command.
MH_INSTANCE="$SLUG"
DATABASE_URL="$DATABASE_URL_VALUE"
AZURE_STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING"
AZURE_STORAGE_CONTAINER="evidence"
LEPTOS_SITE_ADDR="127.0.0.1:$SITE_PORT"
LEPTOS_RELOAD_PORT="$RELOAD_PORT"
EOF
}

# Idempotent: start the containers, refresh .env.local, print where things are.
# Unconditional on every command — a stale .env.local pointing at stopped
# containers otherwise makes the app panic at startup and hang the caller.
# All of it goes to stderr so `dev.sh -- <cmd>` keeps a clean stdout while its
# progress (a first-time seed build takes minutes) still reaches the terminal.
instance_up() {
  {
    db_up; storage_up; write_env_local
    cat <<EOF

  instance      $SLUG
  database      $DB_CONTAINER  (127.0.0.1:$DB_PORT)
  blob storage  $STORAGE_CONTAINER  (127.0.0.1:$BLOB_PORT)
  web server    http://127.0.0.1:$SITE_PORT
  DATABASE_URL  $DATABASE_URL_VALUE

EOF
  } >&2
}

# Readiness contract for automated harnesses: once the site port actually
# accepts connections this prints a single line beginning `MH_READY`. If the
# server dies first it prints `MH_FAILED` and exits non-zero. Wait for one of
# those two tokens — never for an app log line, which may never arrive.
run_and_await_readiness() {
  local host="${LEPTOS_SITE_ADDR%:*}" port="${LEPTOS_SITE_ADDR##*:}" child status

  # Run as a child, not exec, so we can watch for readiness alongside it.
  "$@" &
  child=$!
  # Forward termination so Ctrl-C leaves no orphaned app process.
  trap 'kill -TERM "$child" 2>/dev/null || true' INT TERM

  # Poll the real socket rather than scraping logs: a port that accepts a
  # connection cannot be a false positive.
  until (exec 3<>"/dev/tcp/$host/$port") 2>/dev/null; do
    if ! kill -0 "$child" 2>/dev/null; then
      status=0; wait "$child" 2>/dev/null || status=$?
      [ "$status" -ne 0 ] || status=1
      echo "MH_FAILED dev: server exited before becoming ready (status $status)"
      exit "$status"
    fi
    sleep 0.5
  done

  echo "MH_READY listening on http://$LEPTOS_SITE_ADDR"
  wait "$child"
}

main "$@"
