-- The electronic signature block the Volunteer Agreement now captures: the typed
-- full legal name adopted as a signature, the consent that accompanies it, the
-- parent/guardian details when the volunteer is a minor, and the volunteer's
-- role alongside their existing skills. All defaulted, so rows written before
-- this agreement version stay valid without a backfill.
ALTER TABLE volunteers
    ADD COLUMN volunteer_role         TEXT NOT NULL DEFAULT '',
    -- The full legal name typed into the electronic-signature field.
    ADD COLUMN legal_name             TEXT NOT NULL DEFAULT '',
    ADD COLUMN signature_name         TEXT NOT NULL DEFAULT '',
    -- True when a parent or legal guardian signed on a minor's behalf.
    ADD COLUMN signer_is_guardian     BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN guardian_name          TEXT NOT NULL DEFAULT '',
    ADD COLUMN guardian_relationship  TEXT NOT NULL DEFAULT '',
    ADD COLUMN guardian_email         TEXT NOT NULL DEFAULT '',
    ADD COLUMN electronic_consent     BOOLEAN NOT NULL DEFAULT false,
    -- The autogenerated date and time of submission, part of the audit trail the
    -- consent provision promises to retain.
    ADD COLUMN signed_at              TIMESTAMPTZ;
