-- The Service Agreement now captures an electronic signature block, contact and
-- emergency-contact details, and the services the recipient is asking for. The
-- client twin of `0038_volunteer_signature.sql`.

-- The signed block has to survive the ten-minute email-verification window, the
-- way `intake_json` and `terms_version` already do. JSON of
-- `helpers::client_details::ClientAgreementDetails`; pending rows live minutes,
-- so the default covers anything already in flight.
ALTER TABLE pending_registrations
    ADD COLUMN agreement_details TEXT NOT NULL DEFAULT '{}';

-- One row per signed Service Agreement. `case_id` is nullable for the same
-- reason as `terms_acceptances`: the signature is the person's, and deleting the
-- case it was given for must not erase it.
CREATE TABLE client_agreements (
    user_id                TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    case_id                TEXT REFERENCES cases(id) ON DELETE SET NULL,
    -- Which wording they signed, stored verbatim like `terms_acceptances`.
    terms_version          TEXT        NOT NULL,
    legal_name             TEXT        NOT NULL DEFAULT '',
    signature_name         TEXT        NOT NULL DEFAULT '',
    email                  TEXT        NOT NULL DEFAULT '',
    date_of_birth          DATE,
    phone                  TEXT        NOT NULL DEFAULT '',
    emergency_name         TEXT        NOT NULL DEFAULT '',
    emergency_relationship TEXT        NOT NULL DEFAULT '',
    emergency_phone        TEXT        NOT NULL DEFAULT '',
    -- The ticked services, comma-separated in display order.
    services_requested     TEXT        NOT NULL DEFAULT '',
    electronic_consent     BOOLEAN     NOT NULL DEFAULT false,
    -- All optional: filled only when a parent or guardian signs for a minor.
    minor_name             TEXT        NOT NULL DEFAULT '',
    guardian_name          TEXT        NOT NULL DEFAULT '',
    guardian_relationship  TEXT        NOT NULL DEFAULT '',
    guardian_signature     TEXT        NOT NULL DEFAULT '',
    guardian_email         TEXT        NOT NULL DEFAULT '',
    -- The autogenerated date and time of submission, part of the audit trail the
    -- consent provision promises to retain.
    signed_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX client_agreements_case_idx ON client_agreements (case_id);
